# Loading the Data

In [1]:
import pandas as pd
k=pd.read_csv('hackathon_rentomter_nobroker.csv')
j=pd.read_csv('finaldataset.csv')
k.columns
s=k['rent']
k=k.drop(['rent'],axis=1)
final=pd.concat([k,j],axis=1)
fullfinal=pd.concat([final,s],axis=1)
fullfinal.to_csv('fullfinal.csv',sep='\t')
fullfinal

,id,type,locality,activation_date,latitude,longitude,lease_type,gym,lift,swimming_pool,...,PARK,PB,POOL,RWH,SC,SECURITY,SERVANT,STP,VP,rent
0,ff8081815917971401591af8895032d0,BHK2,Jayanagara,2018-07-05 17:09:49,12.936601,77.576914,FAMILY,0,0,0,...,0,0,0,0,0,0,0,0,0,22000
1,ff80818157dbe1fb0157dc4aa07513dc,BHK2,Basaveshwar Nagar,2017-12-30 17:22:12,12.997989,77.545219,FAMILY,0,0,0,...,1,0,0,0,1,0,0,0,0,20000
2,ff8081815d304406015d30edcd7c4f44,BHK3,"Jaya Nagar East,Jayanagar",2017-07-11 15:42:05,12.935696,77.587642,FAMILY,0,1,0,...,1,1,0,1,1,1,0,0,0,38000
3,ff8081815b106986015b154d908f2ac2,BHK2,Murugeshpalya,2018-07-07 14:26:14,12.953507,77.656118,FAMILY,0,1,0,...,0,1,0,0,0,0,0,0,1,30000
4,ff8081815e80b789015e84a7a42a62a3,BHK2,Whitefield,2017-09-27 12:19:28,12.968520,77.742436,ANYONE,1,1,1,...,1,1,1,1,1,1,1,1,1,26500
5,ff80818162537f2d01625cfb76f37165,BHK2,HSR Layout,2018-03-25 18:15:19,12.921999,77.646238,FAMILY,0,0,0,...,0,0,0,0,0,0,0,0,0,30000
6,ff80818160792cc001608ec7b922154a,BHK3,Harlur,2018-07-26 21:01:47,12.909958,77.674755,FAMILY,0,0,0,...,0,0,0,0,0,1,0,0,0,35500
7,ff8081815bb9ae79015bbd6aae9b03b1,BHK2,Vijaya Nagar,2018-05-19 13:12:15,12.964160,77.518935,FAMILY,0,0,0,...,1,0,0,0,1,0,0,0,0,15000
8,ff808181622f11e901622f590ada0eb9,BHK1,Doddanekkundi,2018-03-20 17:58:57,12.970340,77.688801,FAMILY,0,0,0,...,0,0,0,0,1,1,0,0,0,11000
9,ff8081815dad8e0f015db114d5f90716,BHK2,BTM 2nd Stage,2017-08-18 17:00:23,12.909464,77.609353,ANYONE,0,0,0,...,0,0,0,0,0,0,0,0,0,14000
10,ff8081816165ddca0161696bf0d4056a,BHK2,"EPIP Zone,Whitefield",2018-02-06 12:41:03,12.972033,77.715336,ANYONE,1,1,1,...,1,1,1,1,1,1,1,1,1,26000
11,ff8081815c35329b015c357a6379201f,BHK2,Doddakannelli,2017-12-28 10:06:19,12.909807,77.705232,FAMILY,0,0,0,...,1,0,0,0,1,0,0,0,0,12000
12,ff80818154d230860154e1adf7715d48,BHK2,Whitefield Hope Farm Junction,2018-06-15 19:31:37,12.990748,77.719513,ANYONE,1,1,1,...,1,1,1,1,1,1,0,1,1,27500
13,ff8081815deb30c2015deead2ad13882,BHK2,Whitefield,2017-08-18 15:00:23,12.967221,77.754272,ANYONE,0,0,0,...,0,1,0,0,1,1,0,0,0,13000
14,ff8081815c71b0d0015c71c37acc098a,BHK2,Raja Rajeshwari Nagar,2018-05-29 17:24:24,12.936000,77.517615,ANYONE,0,0,0,...,1,0,0,0,1,0,0,0,0,15000
15,ff80818163ca7f280163ce79cc3431f5,BHK2,Bendre Nagar,2018-06-05 14:04:14,12.913392,77.561954,FAMILY,0,0,0,...,1,0,0,0,1,0,0,0,0,15500
16,ff80818163d92b8e0163dd945aec5a75,BHK2,Brookefield,2018-06-10 19:50:44,12.968715,77.713079,FAMILY,0,0,0,...,1,1,1,0,0,1,0,0,0,22500
17,ff8081815f58e7be015f5ca4cb323344,BHK2,Kumaraswamy Layout,2017-10-27 21:15:43,12.902654,77.564549,FAMILY,0,0,0,...,0,0,0,0,0,0,0,0,0,12000
18,ff808181627abb3d016285a0caa64cd8,BHK2,Whitefield,2018-04-04 16:34:16,12.964323,77.755973,ANYONE,1,1,0,...,1,1,0,0,1,1,0,0,1,16000
19,ff80818164d7894b0164d9c358422ab8,BHK2,Ejipura,2018-07-27 17:25:53,12.938249,77.630912,ANYONE,0,0,0,...,1,0,0,0,1,0,0,0,0,16000
20,ff808181616f685501616f729c5b02bb,BHK2,"Nallurhalli,Whitefield",2018-05-31 10:13:23,12.968408,77.733105,ANYONE,1,1,1,...,1,1,1,1,0,1,0,1,1,28000
21,ff808181638d2a350163909b97eb7088,BHK2,Koramangala,2018-07-11 16:08:21,12.921020,77.633941,ANYONE,0,0,0,...,0,0,0,0,0,0,0,0,0,12500
22,ff8081816483b0ba016484474b646d50,BHK1,Banashankari,2018-07-10 21:56:16,12.934411,77.534592,FAMILY,0,0,0,...,0,0,0,0,0,0,0,0,0,8000
23,ff808181616fc2e801616fdaeb7b0c9c,BHK2,Rajajinagar,2018-02-08 17:51:25,12.989536,77.558938,FAMILY,0,0,0,...,0,0,0,0,0,0,0,0,0,15000
24,ff8081816199fec701619dc4989017fd,BHK3,Basaveshwar Nagar,2018-02-16 15:40:02,12.992381,77.537240,FAMILY,0,0,0,...,0,0,0,0,0,0,0,0,0,18000
25,ff8081815e4ff33e015e50b533893bbb,BHK2,Basaveshwara Nagar,2017-09-05 14:53:51,12.984729,77.543229,ANYONE,0,1,0,...,0,0,0,0,1,1,0,0,1,23000
26,ff808181609db9100160a0ae69db335a,BHK1,Mahadevapura,2017-12-29 20:48:28,12.983019,77.705666,ANYONE,0,0,0,...,0,0,0,1,0,0,0,0,1,12500
27,ff8081815e9f062b015e9f683e9133c2,BHK2,Kasavanahalli,2017-09-22 16:30:24,12.900909,77.674627,ANYONE,1,1,1,...,0,1,1,1,0,1,0,1,1,28000
28,ff808181602754c40160277cc6320a3b,BHK3,"Thigalarapalya,Hoodi",2017-12-05 22:33:17,12.991589,77.727795,COMPANY,0,0,0,...,1,1,1,0,1,1,0,0,0,42000
29,ff8081815e831a26015e864894ea4706,BHK3,Brookefield,2017-09-15 21:50:56,12.956799,77.721080,ANYONE,1,1,1,...,1,1,1,0,0,1,0,0,1,26000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24970,ff80818160c5ed140160cc50993749c5,BHK3,Raja Rajeshwari Nagar,2018-01-06 22:24:55,12.920026,77.519502,FAMILY,0,0,0,...,0,0,0,1,0,1,0,0,1,26000
24971,ff808181579463e5015794f72d6a2249,BHK1,Whitefield,2018-05-08 17:33:41,12.964620,77.755117,ANYONE,0,1,1,...,0,1,1,0,1,1,1,0,1,12500
24972,ff8081815faaa8e4015fb3e14c0f7f4e,BHK3,Banashankari,2017-11-28 16:28:57,12.920494,77.536942,ANYONE,1,1,1,...,0,1,1,0,0,0,0,0,0,50000
24973,ff80818164b1fe850164b24ec7013d24,BHK1,Mahadevapura,2018-07-20 14:43:08,12.991460,77.690995,ANYONE,0,0,0,...,1,0,0,0,1,1,0,0,0,8000
24974,ff808181632559ba01632570627a0797,BHK2,Srinagar,2018-05-28 22:15:25,12.948217,77.550453,FAMILY,0,0,0,...,0,0,0,0,0,0,0,0,0,11000
24975,ff8081815738b8f901573aea427d1538,BHK2,Kaggadasapura,2017-07-26 12:23:52,12.978962,77.679737,FAMILY,0,0,0,...,1,0,0,0,1,0,0,0,0,11000
24976,ff8081816306a0a0016311815ac03971,BHK3,Rajaji Nagar,2018-04-29 19:04:37,12.982311,77.553716,ANYONE,0,0,0,...,0,0,0,0,1,0,0,0,0,25000
24977,ff808181581e52e701581fba19bc1506,BHK3,"Kempapura,Bellandur",2018-02-06 10:49:53,12.946005,77.675063,FAMILY,1,1,0,...,0,1,0,0,0,1,0,0,1,24000
24978,ff8081815d56c69a015d58ff0b261493,BHK3,AECS Layout,2017-07-19 09:50:16,12.963967,77.712034,FAMILY,0,0,0,...,1,0,0,0,1,0,0,0,0,29000
24979,ff8081815fee312e015fee3603950138,BHK3,C V Raman Nagar,2017-11-24 20:16:51,12.983070,77.665434,FAMILY,0,1,0,...,1,1,0,1,1,1,0,0,0,20000
24980,ff80818163e44e860163e7eb0cf94ace,BHK2,"Pattandur Agrahara,Whitefield",2018-06-15 17:46:58,12.977552,77.737544,ANYONE,1,1,0,...,1,1,0,0,0,1,0,1,0,20000
24981,ff8081816128c92e01612c33f1235349,BHK2,"Adarsh Palm Retreat,Bellandur",2018-01-25 13:48:16,12.915500,77.690947,FAMILY,1,1,1,...,0,1,1,1,0,1,1,0,1,28000
24982,ff8081815fd86fcb015fd8edf27b458a,BHK2,JP Nagar 4th Phase,2017-11-20 16:51:32,12.906087,77.599096,ANYONE,0,0,0,...,0,0,0,0,0,0,0,0,0,16500
24983,ff8081815ee7a1c1015eeadcb3565ffa,BHK1,Annasandrapalya Extension,2017-10-05 14:42:18,12.962664,77.674825,ANYONE,0,0,0,...,0,0,0,0,0,0,0,0,0,8000
24984,ff808181626294c5016262c011070c5b,BHK2,Chandra Layout,2018-06-18 20:24:13,12.957574,77.528115,ANYONE,0,0,0,...,1,0,0,0,1,1,0,0,0,15000
24985,ff8081815cab88b6015caf5cd2fc1571,BHK2,Nagarbhavi,2017-11-05 18:23:25,12.958733,77.511201,ANYONE,0,0,0,...,1,0,0,0,1,0,0,0,0,16000
24986,ff80818160b5a24e0160b5c74b1210a7,BHK2,Cox Town,2018-03-07 17:21:04,12.993595,77.619263,ANYONE,0,0,0,...,1,0,0,1,1,0,0,1,0,27000
24987,ff80818154a96e170154aedc92a45149,BHK2,Nagarbhavi,2018-02-24 18:10:27,12.967849,77.501832,FAMILY,0,0,0,...,0,0,0,1,0,0,0,0,0,9000
24988,ff8081815a21c1b1015a229b61fd1cc7,BHK2,BTM 2nd Stage,2017-11-15 12:12:35,12.916151,77.610446,ANYONE,0,0,0,...,0,1,0,0,0,0,0,0,0,18000
24989,ff8081815a36829d015a37296ebb3959,BHK2,JP Nagar,2018-07-03 17:13:38,12.900713,77.586913,ANYONE,0,1,0,...,0,0,0,0,0,1,0,0,0,15000
24990,ff8081815ea438c1015ea88c982767de,BHK1,Banashankari Stage I,2017-09-22 14:40:49,12.934247,77.557453,ANYONE,0,0,0,...,0,0,0,1,1,0,0,0,0,9000
24991,ff8081815ee79ffb015eec214c7664ce,BHK2,Hosakerehalli,2017-10-06 12:16:58,12.920863,77.536637,FAMILY,0,0,0,...,0,0,0,0,0,0,0,0,0,15000
24992,ff808181644f763e016450412c251cdc,BHK2,Whitefield,2018-07-10 20:19:33,12.976795,77.742155,COMPANY,0,1,1,...,1,1,1,1,1,1,0,0,1,26000
24993,ff80818159e9b2510159ee752c932ba6,BHK3,RR Nagar,2018-07-04 13:15:00,12.931373,77.515560,FAMILY,0,0,0,...,1,0,0,1,1,0,0,0,1,20000
24994,ff8081815d65f47a015d66011fb70179,BHK3,Whitefield,2018-07-03 17:10:46,12.983226,77.743941,ANYONE,1,1,1,...,1,1,1,1,1,1,0,1,1,35000
24995,ff8081816306a4ae0163110a418843b3,BHK2,Doddanekundi,2018-04-29 17:59:43,12.969708,77.688017,ANYONE,0,1,0,...,0,1,0,1,0,1,0,0,1,20000
24996,ff8081815e14c7fe015e19124d9548f0,BHK1,C V Raman Nagar,2017-08-25 18:07:29,12.992878,77.665004,FAMILY,0,0,0,...,0,0,0,0,1,0,0,0,0,9500
24997,ff808181633148de01633a044b6a442a,BHK1,Mahadevapura,2018-05-29 15:59:30,12.992564,77.666543,ANYONE,0,0,0,...,1,0,0,0,1,0,0,0,0,8000
24998,ff8081815f58e7be015f5be9e1155e86,BHK1,Suddagunte Palya,2018-03-11 19:36:17,12.931328,77.603983,ANYONE,0,0,0,...,0,0,0,0,1,0,0,0,0,9000
24999,ff80818162f796ab0162fda4df8e2dac,BHK2,Munnekollal,2018-04-27 10:43:07,12.946809,77.715234,FAMILY,0,1,0,...,0,1,0,0,0,1,0,1,0,22000

In [2]:
#Loading libraries 
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0)
import seaborn as sns
from scipy import stats
from scipy.stats import norm

# Data Preprocessing

In [3]:
fullfinal.drop(['id','locality','activation_date','amenities'],axis = 1, inplace = True)

In [4]:
X = fullfinal.iloc[:, :-1].values
print(X.shape)

(25000, 40)

In [5]:
#getting the last column to predict
y = fullfinal.iloc[:, -1].values

In [6]:
print(X[0])

['BHK2' 12.93660072001916 77.57691394334313 'FAMILY' 0 0 0 0
 'SEMI_FURNISHED' 'TWO_WHEELER' 1000 5.0 2 'S' 2.0 2 2.0 'CORP_BORE' 'IF'
 1.0 220000.0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

# Encoding categorical data

In [7]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 0] = labelencoder_X_1.fit_transform(X[:, 0])

labelencoder_X_2 = LabelEncoder()
X[:, 3] = labelencoder_X_2.fit_transform(X[:, 3])

labelencoder_X_3 = LabelEncoder()
X[:, 8] = labelencoder_X_3.fit_transform(X[:, 8])

labelencoder_X_4 = LabelEncoder()
X[:, 9] = labelencoder_X_4.fit_transform(X[:, 9])

labelencoder_X_5 = LabelEncoder()
X[:, 13] = labelencoder_X_5.fit_transform(X[:, 13])

labelencoder_X_6 = LabelEncoder()
X[:, 17] = labelencoder_X_6.fit_transform(X[:, 17])

labelencoder_X_7 = LabelEncoder()
X[:, 18] = labelencoder_X_7.fit_transform(X[:, 18])

In [8]:
X.shape

(25000, 40)

In [9]:
#one hot encoding
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
onehotencoder = OneHotEncoder(categorical_features = [3])
X = onehotencoder.fit_transform(X).toarray()
onehotencoder = OneHotEncoder(categorical_features = [8])
X = onehotencoder.fit_transform(X).toarray()
onehotencoder = OneHotEncoder(categorical_features = [9])
X = onehotencoder.fit_transform(X).toarray()
onehotencoder = OneHotEncoder(categorical_features = [13])
X = onehotencoder.fit_transform(X).toarray()
onehotencoder = OneHotEncoder(categorical_features = [17])
X = onehotencoder.fit_transform(X).toarray()
onehotencoder = OneHotEncoder(categorical_features = [18])
X = onehotencoder.fit_transform(X).toarray()

In [10]:
X.shape

(25000, 52)

# spliting the data

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [12]:
print(X_train)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 1. 1.]
 [0. 1. 0. ... 0. 1. 0.]
 [1. 0. 1. ... 0. 0. 0.]]

# Training Dataset on different Algorithm and checking the accuracy

# Linear Regression

In [13]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

/usr/local/lib/python3.5/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [14]:
y_pred = regressor.predict(X_test)
print('Liner Regression R squared: %.4f' % regressor.score(X_test, y_test))

Liner Regression R squared: 0.6223

# RandomForest Regressor

In [15]:
from sklearn.ensemble import RandomForestRegressor

forest_reg = RandomForestRegressor(random_state=42)
forest_reg.fit(X_train, y_train)

/usr/local/lib/python3.5/dist-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=42, verbose=0, warm_start=False)

In [16]:
print('Random Forest R squared": %.4f' % forest_reg.score(X_test, y_test))

Random Forest R squared": 0.7871

# GradientBoosting Regressor

In [17]:
from sklearn import ensemble
from sklearn.ensemble import GradientBoostingRegressor
model = ensemble.GradientBoostingRegressor()
model.fit(X_train, y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='ls', max_depth=3, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=100, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False)

In [18]:
print('Gradient Boosting R squared": %.4f' % model.score(X_test, y_test))

Gradient Boosting R squared": 0.8046

In [19]:
print("Accuraccy",model.score(X_test,y_test)*100)

Accuraccy 80.4625400383517

In [20]:
y_pred=model.predict(X_test)
y_pred

array([42136.224506  , 32136.09379653,  9841.87293664, ...,
       33804.83344394, 16428.71606133,  9851.76430125])

In [23]:
import pickle
# save model to file
pickle.dump(model, open("model.pkl", "wb"))

In [22]:
# load model from file
loaded_model = pickle.load(open("model.pkl", "rb"))